from typing import Protocol, runtime_checkable

@runtime_checkable
class MetricsCollector(Protocol):
    def record_cache_hit(self, similarity: float, latency_ms: float, source: str) -> None: ...
    def record_cache_miss(self, latency_ms: float, source: str) -> None: ...
    def record_put(self, latency_ms: float) -> None: ...
    def record_timeout(self, operation: str) -> None: ...
    def record_error(self, operation: str, error_type: str) -> None: ...